// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_Team9.Models;

#nullable disable

namespace Mission08_Team9.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20250228052115_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Mission08_Team9.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission08_Team9.Models.ToDoTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-01",
                            Quadrant = 1,
                            TaskName = "Pay utility bills"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Completed = 0,
                            DueDate = "2025-03-05",
                            Quadrant = 1,
                            TaskName = "Finish IS 413 homework"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-10",
                            Quadrant = 2,
                            TaskName = "Prepare for work presentation"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 4,
                            Completed = 0,
                            DueDate = "2025-03-15",
                            Quadrant = 2,
                            TaskName = "Read book on leadership"
                        });
                });

            modelBuilder.Entity("Mission08_Team9.Models.ToDoTask", b =>
                {
                    b.HasOne("Mission08_Team9.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
