// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_Team9.Models;

#nullable disable

namespace Mission08_Team9.Migrations
{
    [DbContext(typeof(TaskContext))]
    partial class TaskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Mission08_Team9.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission08_Team9.Models.ToDoTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-01",
                            Quadrant = 1,
                            TaskName = "Pay utility bills"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Completed = 0,
                            DueDate = "2025-03-05",
                            Quadrant = 1,
                            TaskName = "Finish IS 413 homework"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-02",
                            Quadrant = 1,
                            TaskName = "Call doctor for appointment"
                        },
                        new
                        {
                            TaskId = 4,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-10",
                            Quadrant = 1,
                            TaskName = "Submit tax documents"
                        },
                        new
                        {
                            TaskId = 5,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-10",
                            Quadrant = 2,
                            TaskName = "Prepare for work presentation"
                        },
                        new
                        {
                            TaskId = 6,
                            CategoryId = 4,
                            Completed = 0,
                            DueDate = "2025-03-15",
                            Quadrant = 2,
                            TaskName = "Read book on leadership"
                        },
                        new
                        {
                            TaskId = 7,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-12",
                            Quadrant = 2,
                            TaskName = "Exercise for 30 mins"
                        },
                        new
                        {
                            TaskId = 8,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-04-01",
                            Quadrant = 2,
                            TaskName = "Plan summer vacation"
                        },
                        new
                        {
                            TaskId = 9,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-06",
                            Quadrant = 3,
                            TaskName = "Reply to random emails"
                        },
                        new
                        {
                            TaskId = 10,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-07",
                            Quadrant = 3,
                            TaskName = "Attend unnecessary meeting"
                        },
                        new
                        {
                            TaskId = 11,
                            CategoryId = 2,
                            Completed = 0,
                            DueDate = "2025-03-08",
                            Quadrant = 3,
                            TaskName = "Fix minor bug in personal project"
                        },
                        new
                        {
                            TaskId = 12,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-09",
                            Quadrant = 3,
                            TaskName = "Help friend move furniture"
                        },
                        new
                        {
                            TaskId = 13,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-20",
                            Quadrant = 4,
                            TaskName = "Watch Netflix series"
                        },
                        new
                        {
                            TaskId = 14,
                            CategoryId = 3,
                            Completed = 0,
                            DueDate = "2025-03-21",
                            Quadrant = 4,
                            TaskName = "Scroll through social media"
                        },
                        new
                        {
                            TaskId = 15,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-22",
                            Quadrant = 4,
                            TaskName = "Rearrange bookshelf"
                        },
                        new
                        {
                            TaskId = 16,
                            CategoryId = 1,
                            Completed = 0,
                            DueDate = "2025-03-23",
                            Quadrant = 4,
                            TaskName = "Play video games"
                        });
                });

            modelBuilder.Entity("Mission08_Team9.Models.ToDoTask", b =>
                {
                    b.HasOne("Mission08_Team9.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
